# Bölüm 1: Elasticsearch Dünyasına Merhaba De!
# HTTP Request Örnekleri

###
# 1. Cluster Sağlığını Kontrol Et
GET http://localhost:9200/_cluster/health

###
# 2. Node'ları Listele
GET http://localhost:9200/_cat/nodes?v&h=ip,name,heap.percent,load_1m

###
# 3. Mevcut Index'leri Listele
GET http://localhost:9200/_cat/indices?v
