version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4 # Güncel stabil sürümü kontrol edin
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Eğitim kolaylığı için security kapalı, production'da açık olmalı!
      - ES_JAVA_OPTS=-Xms1g -Xmx1g # Kaynaklara göre ayarlanabilir
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4 # Elasticsearch ile aynı sürüm olmalı
    container_name: kib01
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
  elastictraining:
    build:
      context: ../src/ElasticTraining
      dockerfile: Dockerfile
    image: elastictraining:latest
    container_name: elastictraining
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Elasticsearch__Uri=http://es01:9200
    depends_on:
      - elasticsearch
volumes:
  esdata01:
    driver: local
